[workspace]
resolver = "3"
members = [
  "inspect_embassy",
  "gdb_backend",
  "probe_rs_backend",
]
exclude = [
  "test_crates"
]

[workspace.dependencies]

inspect_embassy = { path = "inspect_embassy" }
