[workspace]
resolver = "3"
members = [
  "embassy_inspect",
  "gdb_backend",
  "probe_rs_backend",
]
exclude = [
  "test_crates"
]

[workspace.dependencies]

embassy_inspect = { path = "embassy_inspect" }
