[package]
name = "probe_rs_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
inspect_embassy = { workspace = true }

probe-rs = "0.29.1"
clap = { version = "4", features = ["derive", "env"] }
ratatui = "0.29.0"
thiserror = "2.0.16"
anyhow = "1.0.98"
log = "0.4.27"
